<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        
        <title>LoyAlerts – Medical treatments can be more efficient!
        </title>
        
        <style>
           p {
                font-family: verdana;
                font-size: 16px;
                line-height: 1.5em;
           }
           #pagina {
               margin: auto;
           }
           #div-h1 {
                border-bottom: 1px solid #ccc;
				clear: both;
				height: 120px;
           } 
           #div-h2 {
                height: 250px;
                
           }
           #imagem-h2 {
                float: left;
                padding-right: 5px;
                height: 240px;
           }
           #texto-h2 {
                font-family: verdana;
                font-size: 35px;
                font-weight: bold;
                color: rgb(66,107,28);
                text-shadow: 2px 1px black;
                text-align: center;
           }
           #div-par1 {
                background-color: rgb(66, 107, 28);
                color: rgb(242, 242, 242);
                height: 250px;
                
           }
           #texto-par1 {
                text-align: center;
                padding: 60px;
                margin-bottom: 0px;
           } 
           #div-par2 {
            height: 310px;
           }
           #imagem-par2 {
                float: right;
                height: 250px;
                padding-left: 10px;
           }
           #texto-par2 {
                text-align: center;
                padding: 30px;
           }
           #div-contato {
               height: 90px;
               background-color: rgb(113,122,128);
               clear: both;
           }
           #texto-contato1 {
               color: rgb(46, 107, 28);
               text-shadow: 1px 1px black;
               text-align: center;
               padding-top: 25px;
           }
           #texto-contato2 {
               color: rgb(46, 107, 28);
               text-align: right;
               font-size: 9px; 
           }
           .login-error {
                    float:left;
                    width:50%;
                    color:#ef7474
                }
           .img-field {
                    float:left;					
                    width:33%;
                }
           .img-field > img {
                   margin: 40px 9px 9px;
                }
                .login-field{
                    float:right;
                    margin:9px;
                }
                .login-field > form > input[type="text"],.login-field > form > input[type="password"]{
                    border: 1px solid #ccc;
					border-radius: 4px;
					margin: 4px 4px 4px 0;
					padding: 7px;
                }
      
                .formElementSubmit {
                    background: rgba(0, 0, 0, 0) url("../images/public/acesso.png") no-repeat scroll left top;
                    border: medium none;
                    color: #616a58;
                    height: 21px;
                    padding-bottom: 4px;
                    text-indent: 0;
                    width: 55px;
                    border-radius: 6px;
                    cursor: pointer;
                }
                .forgot-password{
                    color: #a9b999;
                     font-size: 15px;
                }
        </style>
        <script>
            var sizeVal = window.screen.availWidth/96;
        if(sizeVal <= 9.5){
            window.location.href = "<?php echo '/default'; ?>";
        }
        </script>
    </head>
    <body>
        <div id= "pagina">
        <div id= "div-h1">
        <div class="img-field">
         <img src="<?php echo $this->logo; ?>">
        </div>
            <div class="login-error">
                <?php if (!empty($this->formResponse)): ?>
                <div style="width:30%;float:right">
        <strong><?= $this->formResponseTitle; ?></strong>
        <br><?= $this->formResponse; ?></div>
<?php endif; ?>
            </div>
        <div class="login-field">
            <form method="post" action='/landing/index'>
            <input type="text" name="email" placeholder="E-mail*"/>
            <br>
            <input type="password" name="password" placeholder="Password*"/>
            <br>
            <input type="submit" value="Login" class="formElementSubmit">
            <a href="/password/index" class='forgot-password'>Forgot my password</a>
            </form>
            
        </div>
        </div>
        
        <div id= "div-h2"><h2> 
        <p id= "texto-h2"><img id= "imagem-h2" src="<?php echo $this->image1; ?>" alt="Imagem de paciente segurando medicamento">Higher adherence means more <br>treatments with great results!</p>
            
        </h2></div>
        
        <div id= "div-par1"><p id= "texto-par1">LoyAlerts helps patients to remember the correct dates and times to take their prescripted medication by generating alerts on their smartphones. The alerts can be scheduled by physicians or other designated health professional from this website, by fulfilling an intuitive and extremely fast form. Patients that are unfamiliar with technologies or just too busy to spend time with schedules will certainly appreciate this new experience, as the only thing they will do is to download our app.</p></div>
        
        <div id= "div-par2"><p id= "texto-par2"> <img id= "imagem-par2" src="<?php echo $this->image2; ?>" alt="Imagem de paciente tomando medicamento"> LoyAlerts main goal is to improve the adherence in medical treatments. By helping patients to take their medication correctly, professionals notice that treatments with great results become more frequent. LoyAlerts helps building safer and more efficient medical treatments, consequently improving patients life quality.
        </p></div>
        
        <div id= "div-contato"><p id= "texto-contato1">Click <a href= "mailto:vendas@lembrefacil.com.br?subject=ContatoSite">here</a> to request a free license!</p>
        <p id= "texto-contato2"> © Copyright 2017 LoyAlerts – All rights reserved.</p>
        </div>
        </div>
    </body>
</html>